BROKER_IP = '192.168.218.111'
SEND_UID = b'gate/send-uid'
SEND_UID_RESPONSE = b'gate/send-uid/response'
REQUEST_ID = b'register/request-id'
REQUEST_ID_RESPONSE = b'register/request-id/response'
RECEIVE_ID = b'register/receive-id'
REGISTER_CARD = b'gate/register'
REGISTER_CARD_RESPONSE = b'gate/register/response'
