@startuml

package Garage {
    package Thing(Parking) {
        component "Ultrasonic Sensor" as sensor
        component "PyCom" as py
        component "Light" as actuator

        sensor <-d-> py : checking depth
        actuator <-l- py : availability light
    }

    package Thing(Gate) {
        component "RFID Sensor" as sensor2
        component "PyCom" as py2
        component "Servo Motor" as actuator2

        sensor2 <-d-> py2 : read chip
        actuator2 <-r- py2 : open gate
    }

    package Gateway {
        component "MQTT Broker" as broker
        component Distributor as distributor
    }

    py <-d-> broker
    py2 <-d-> broker : Wi-Fi (MQTT)
    broker <-r-> distributor : Wi-Fi (MQTT)
}

package Cloud {
    database "Firebase Realtime DB" as realtimedb
    database "Firebase Document DB" as documentdb

    component API as api

    component WebUI as web

    api <-l-> web : sockets
    api <-l-> web : http
    api <-d-> realtimedb : availability
    api <-d-> documentdb : historic data

    distributor <--> api : sockets
}

@enduml
